project:
  type: website

website:
  title: "Vietnam PCI Influence Analysis"
  navbar:
    left:
    - href: aboutus.qmd
      text: About Us
    - href: project.qmd
      text: Project
    - href: poster.qmd
      text: Poster
    - href: user_guide.qmd
      text: User Guide
    - text: Shiny Application
      href: https://is415-gaa.shinyapps.io/VietnamPCIInfluence/
      target: _blank
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

